### ISSUE TITLE
configure program natlink

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlinkcore#11]
In a separate folder, NatlinkConfigure, the natlinkconfigfunctions.py are now doing most of their work. I will complete this part.

After that, enhancing the gui, configurenatlink.pyw should be tackled, or a complete new gui. Aaron opted for that one, but I can try how far I come with the existing gui.

Doug, could you include the config program as a post processing option in the install procedure, with the inno setup procedure. Provided you can also compile the natlink installer with Visual Studio.

**Comment by LexiconCode** [comment]
Done in https://github.com/dictation-toolbox/natlinkcore/pull/1
