### ISSUE TITLE
commented out code in __init__.py

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlinkcore#48]
```

# from .config import NoGoodConfigFoundException
# from .loader import NatlinkMain
# from .loader import run as run_loader
# from .redirect_output import redirect as redirect_all_output_to_natlink_window
```

I suspect it is cruft and shoudl be deleted?  

also maybe teh find-in-site-packages could be toasted?

**Comment by quintijn** [comment]
I think I stripped the code ok.

The all testing procedure fails at some points, tests_natlinktimer.py should be checked for the "stop clause".

So, I will PR this, but leave this issue open.

**Comment by quintijn** [comment]
completed...

**Comment by quintijn** [comment]
test setTrayIcon moved to natlink
