### ISSUE TITLE
Defaults for [settings.debugadapterprotocol]

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlinkcore#66]
These should be the defaults for that section, 
`[settings.debugadapterprotocol]
dap_enabled = False
dap_port = 7474
dap_wait_for_debugger_attach_on_startup = False`

dap_wait_for_debugger_attach_on_startup = True is the current default, should be false.

**Comment by quintijn** [comment]
Hi Doug, I hope you are working on correcting the problem with loader.py?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\loader.py", line 671, in run
    dh = OutputDebugStringHandler()
NameError: name 'OutputDebugStringHandler' is not defined
```

**Comment by quintijn** [comment]
You apparently fixed this, Doug. I made the default port 7474 in the config.py (line80) as you requested earlier. Will be merged in when doing a PR... OK?
